config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  resources :docs

  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index' 
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doc_controller.rb
class DocController < ApplicationController
  def index
    
  end

  def show
    
  end

  def new
    
  end

  def create
    
  end

  def edit
    
  end

  def update
    
  end

  def destroy
    
  end

  private
    
    def find_doc
      
    end

    def doc_params
      
    end

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show

  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render :edit
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
    
    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: 'button'

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Edit Doc

  = render 'form'
  = link_to "Cancel", docs_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      -  @docs.each do |doc|
        %a{ href: (url_for [doc]) }
          %p.title= doc.title
          %p.date= time_ago_in_words(doc.created_at)
          %p.content= truncate(doc.content, length: 70)

    - else
      %h2 Create a Doc!
      %p Start Creating Documents and Organizing Your Life!

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc

  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    .title= @doc.title
    .p= simple_format @doc.content

    .buttons
      = link_to "Edit Doc", edit_doc_path(@doc), class: 'button'
      = link_to "Move To Trash", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: 'button'

app/views/layouts/application.html.haml
!!!
%html
%head
  %title FileCabinet | All your documents in one place!
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 

%body 
  %header 
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Create New Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Log In", new_user_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/welcome/index.html.haml
#banner 
  .banner_content
    %h1 FileCabinet
    %p Your files always organized.

    %button= link_to "Create a Account", new_user_registration_path

#callouts
  .callout_inner
    .wrapper  
      .callout 
        %h2 Organize 
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id enim non ante ornare molestie ut eu velit. Nullam faucibus mi et felis auctor, facilisis accumsan odio rhoncus. Integer consectetur, ante cursus condimentum tempus, sapien neque fringilla quam, ac ornare sem quam eget mi.  Vestibulum venenatis magna non mauris volutpat maximus. Curabitur congue libero eget nisl lobortis volutpat. Praesent orci turpis, porta eu porttitor eget, viverra malesuada magna. Mauris fermentum ullamcorper tellus ac condimentum. Etiam malesuada nec tellus eget vulputate. Aliquam egestas erat ac odio imperdiet, quis gravida velit convallis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

#bottom_cta
  .wrapper 
    %h2 Go Ahead!
    %br 
    %button= link_to "Join Now", new_user_registration_path